EVE/Controllers/BusDriversController.cs
using EVE.Data;
using EVE.Data.Services;
using EVE.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EVE.Controllers
{
    public class BusDriversController : Controller
    {
        private readonly IBusDriversService _service;

        public BusDriversController(IBusDriversService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }
        //Get request Actors/Create
        public  IActionResult Create ()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create ([Bind("Emri,BusDriverPic,Bio")]BusDriver driver)
        {
             if (!ModelState.IsValid)
            {
                return View(driver);
            }
            await _service.AddAsync(driver);
            return RedirectToAction(nameof(Index));
        }

        //Get: BusDrivers/Details/1 <-- ID
        public async Task<IActionResult> Details (int id)
        {
            var driverDetails = await _service.GetByIdAsync(id);

            if (driverDetails == null) return View("NotFound");
            return View(driverDetails);
        }

        //Get request Actors/Create
        public async Task< IActionResult> Edit(int id)
        {
            var driverDetails = await _service.GetByIdAsync(id);

            if (driverDetails == null) return View("NotFound");
            return View(driverDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Emri,BusDriverPic,Bio")] BusDriver driver)
        {
            if (!ModelState.IsValid)
            {
                return View(driver);
            }
            await _service.UpdateAsync(id, driver);
            return RedirectToAction(nameof(Index));
        }

        //Get request Actors/Delete/1 <-- Me fshi
        public async Task<IActionResult> Delete(int id)
        {
            var driverDetails = await _service.GetByIdAsync(id);

            if (driverDetails == null) return View("NotFound");
            return View(driverDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var driverDetails = await _service.GetByIdAsync(id);
            if (driverDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

EVE/Controllers/BusInfosController.cs
using EVE.Data;
using EVE.Data.Services;
using EVE.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EVE.Controllers
{
    public class BusInfosController : Controller
    {
        private readonly IBusInfoService _service;

        public BusInfosController (IBusInfoService service)
        {
            _service = service;
        }

        public async Task< IActionResult> Index()
        {
            var allBuses = await _service.GetAllAsync();
            return View(allBuses);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var allBuses = await _service.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allBuses.Where(n => n.BusType.ToLower().Contains(searchString.ToLower()) || n.Pershkrimi.ToLower().Contains(searchString.ToLower())).ToList();
                return View("Index", filteredResult);
            }

            return View(allBuses);
        }

        //GET: BusInfos/Details/1 <-- Details te BusInfos
        public async Task <IActionResult> Details(int id)
        {
            var BusInfoDetail = await _service.GetBusInfoByIdAsync(id);
            return View(BusInfoDetail);
        }

        //GET: BusInfos/Create <-- Krijimi i nje BusInfo te re
        public async Task<IActionResult> Create()
        {
            var busInfoDropDownsData = await _service.GetNewBusInfoDropDownValues();
            ViewBag.BusDrivers = new SelectList(busInfoDropDownsData.BusDrivers, "ID", "Emri");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewBusInfoVM busInfo)
        {
            if (!ModelState.IsValid)
            {
                var busInfoDropDownsData = await _service.GetNewBusInfoDropDownValues();
                ViewBag.BusDrivers = new SelectList(busInfoDropDownsData.BusDrivers, "ID", "Emri");
                return View(busInfo);
            }

            await _service.AddNewBusInfoAsync(busInfo);
            return RedirectToAction(nameof(Index));
        }
        //Get
        public async Task<IActionResult> Edit(int id)
        {

            var busDetails = await _service.GetBusInfoByIdAsync(id);

            if (busDetails == null) return View("NotFound");

            var response = new NewBusInfoVM()
            {
                ID = busDetails.ID,
                BusCategory = busDetails.BusCategory,
                BusPhoto = busDetails.BusPhoto,
                BusType = busDetails.BusType,
                Pershkrimi = busDetails.Pershkrimi,
                StartLineDate = busDetails.StartLineDate,
                EndLineDate = busDetails.EndLineDate,
                TicketPrice = busDetails.TicketPrice,
                BusDriverIDs = busDetails.BusDrivers_BusInfos.Select(n => n.BusDriverID).ToList(),

            };



            var busInfoDropDownsData = await _service.GetNewBusInfoDropDownValues();
            ViewBag.BusDrivers = new SelectList(busInfoDropDownsData.BusDrivers, "ID", "Emri");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewBusInfoVM businfo)
        {

            if (id != businfo.ID) return View("NotFound");
            if (!ModelState.IsValid)
            {
                var busInfoDropDownsData = await _service.GetNewBusInfoDropDownValues();
                ViewBag.BusDrivers = new SelectList(busInfoDropDownsData.BusDrivers, "ID", "Emri");
                return View(businfo);
            }

            await _service.UpdateBusInfoAsync(businfo);
            return RedirectToAction(nameof(Index));
        }


    }
}
 

EVE/Controllers/OrdersController.cs
using EVE.Data.Cart;
using EVE.Data.Services;
using EVE.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace EVE.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IBusInfoService _busInfoService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;
        public OrdersController(IBusInfoService busInfoService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _busInfoService = busInfoService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task <IActionResult> Index ()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }


        public IActionResult ShoppingCart()
        {
            var tickets = _shoppingCart.GetTicketCarts();
            _shoppingCart.TicketCarts = tickets;
            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task <IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _busInfoService.GetBusInfoByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.AddTicketToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _busInfoService.GetBusInfoByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveTicketFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }


        public async Task <IActionResult> CompleteOrder ()
        {
            var items = _shoppingCart.GetTicketCarts();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);


            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();
            return View("OrderCompleted");
        }


    }
}

EVE/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">Kjo faqe nuk ekziston!</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="BusDrivers" asp-action="Index">Home Page</a>
    </div>
</div>

EVE/Views/Shared/_CreateItem.cshtml
@model string;

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle">sAdd new</i>
        </a>
    </div>
}

EVE/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding: 5px;"></span>

    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
}
else
{

    @*User profile section*@
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i> Orders
                </a>
            </li>

            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people"></i> Users
                    </a>
                </li>
            }
        </ul>
    </div>
    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
}

EVE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EVE</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="BusInfos" asp-action="Index">EVE</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BusDrivers" asp-action="Index"> Bus Drivers</a>
                            </l i>
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="BusDrivers" asp-action="Index"> <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/OOjs_UI_icon_userAvatar.svg/1200px-OOjs_UI_icon_userAvatar.svg.png" style="width:25px; height:25px;"  /> Bus Drivers</a>
                                    <a class="dropdown-item" asp-controller="BusInfos" asp-action="Index"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Bus-logo.svg/681px-Bus-logo.svg.png " style="width:25px; height:25px;" /> Bus Infos</a>

                                </div>
                            </li>
                        }


                        </ul>
                    <form class="form-inline my-2 my-lg-0" asp-controller="BusInfos" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a Line" aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("TIcketsCartSummary")
                    </ul>

                    <partial name="_Identity.cshtml" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EVE - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>